services:
  mongodb:
    image: mongo:7.0
    container_name: fintrack-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: FinTrackDb
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fintrack-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  rabbitmq-data:
